package com.carfind.config;

import com.carfind.entity.Car;
import com.carfind.repository.CarRepository;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final CarRepository carRepository;

    @Override
    public void run(String... args) {
        if (carRepository.count() > 0) {
            return;
        }

        carRepository.saveAll(List.of(
                Car.builder()
                        .name("Creta")
                        .brand("Hyundai")
                        .priceMin(10.99)
                        .priceMax(20.15)
                        .safetyRating(5)
                        .mileage(17.4)
                        .fuelType("PETROL")
                        .segment("COMPACT_SUV")
                        .bootSpace(433)
                        .bestVariant("SX(O) Knight Diesel DCT")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("Nexon")
                        .brand("Tata")
                        .priceMin(8.15)
                        .priceMax(15.60)
                        .safetyRating(5)
                        .mileage(17.4)
                        .fuelType("PETROL")
                        .segment("COMPACT_SUV")
                        .bootSpace(350)
                        .bestVariant("Fearless Plus S Dark Edition")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(false)
                        .build(),
                Car.builder()
                        .name("Seltos")
                        .brand("Kia")
                        .priceMin(10.90)
                        .priceMax(20.45)
                        .safetyRating(5)
                        .mileage(16.8)
                        .fuelType("PETROL")
                        .segment("COMPACT_SUV")
                        .bootSpace(433)
                        .bestVariant("GTX Plus AT")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("XUV700")
                        .brand("Mahindra")
                        .priceMin(13.99)
                        .priceMax(26.99)
                        .safetyRating(5)
                        .mileage(15.0)
                        .fuelType("DIESEL")
                        .segment("FULL_SUV")
                        .bootSpace(469)
                        .bestVariant("AX7L Luxury Pack")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("City")
                        .brand("Honda")
                        .priceMin(11.63)
                        .priceMax(16.98)
                        .safetyRating(4)
                        .mileage(17.8)
                        .fuelType("PETROL")
                        .segment("SEDAN")
                        .bootSpace(506)
                        .bestVariant("ZX CVT")
                        .sunroof(true)
                        .adas(true)
                        .cam360(false)
                        .ventilatedSeats(false)
                        .build(),
                Car.builder()
                        .name("Fronx")
                        .brand("Maruti Suzuki")
                        .priceMin(7.52)
                        .priceMax(13.04)
                        .safetyRating(3)
                        .mileage(21.5)
                        .fuelType("PETROL")
                        .segment("HATCHBACK")
                        .bootSpace(308)
                        .bestVariant("Alpha Turbo AT")
                        .sunroof(true)
                        .adas(false)
                        .cam360(false)
                        .ventilatedSeats(false)
                        .build(),
                Car.builder()
                        .name("Innova Hycross")
                        .brand("Toyota")
                        .priceMin(18.64)
                        .priceMax(30.26)
                        .safetyRating(5)
                        .mileage(21.1)
                        .fuelType("HYBRID")
                        .segment("MUV")
                        .bootSpace(300)
                        .bestVariant("ZX(O) Hybrid")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("Hector")
                        .brand("MG")
                        .priceMin(14.00)
                        .priceMax(22.68)
                        .safetyRating(4)
                        .mileage(14.0)
                        .fuelType("PETROL")
                        .segment("MID_SUV")
                        .bootSpace(587)
                        .bestVariant("Savvy Pro CVT")
                        .sunroof(true)
                        .adas(true)
                        .cam360(true)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("Virtus")
                        .brand("Volkswagen")
                        .priceMin(11.36)
                        .priceMax(19.51)
                        .safetyRating(5)
                        .mileage(18.5)
                        .fuelType("PETROL")
                        .segment("SEDAN")
                        .bootSpace(521)
                        .bestVariant("GT Plus DSG")
                        .sunroof(true)
                        .adas(true)
                        .cam360(false)
                        .ventilatedSeats(true)
                        .build(),
                Car.builder()
                        .name("Kushaq")
                        .brand("Skoda")
                        .priceMin(11.59)
                        .priceMax(20.15)
                        .safetyRating(5)
                        .mileage(18.0)
                        .fuelType("PETROL")
                        .segment("COMPACT_SUV")
                        .bootSpace(385)
                        .bestVariant("Monte Carlo 1.5 TSI DSG")
                        .sunroof(true)
                        .adas(true)
                        .cam360(false)
                        .ventilatedSeats(true)
                        .build()
        ));
    }
}
